# This file is managed by 'repo_helper'. Don't edit it directly.
---
name: Linux

on:
  push:

jobs:
  tests:
    name: "ubuntu-20.04 / Python ${{ matrix.config.python-version }}"
    runs-on: "ubuntu-20.04"
    continue-on-error: ${{ matrix.config.experimental }}
    env:
      USING_COVERAGE: '3.6'

    strategy:
      fail-fast: False
      matrix:
        config:
          - {python-version: "3.6", testenvs: "py36,build", experimental: False}

    steps:
      - name: Checkout 🛎️
        uses: "actions/checkout@v2"

      - name: Setup Python 🐍
        uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.config.python-version }}"

      - name: Install dependencies 🔧
        run: |
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade tox virtualenv

      - name: "Run Tests for Python ${{ matrix.config.python-version }}"
        run: python -m tox -e "${{ matrix.config.testenvs }}"
